config/routes.rb
Rails.application.routes.draw do

  root to: "pages#market"
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :locations do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :index, :destroy]

  # resources :devices, only: [:new, :create]

  resources :pets, only: [:new, :create, :edit, :update, :destroy]
  # resources :users, only: [:show, :edit, :update]

  resources :location, only: [:show]


  get '/profile', to: 'pages#profile', as: 'profile'
  get '/profile/:id', to: 'pages#profile', as: 'profile_show'


  # resources :users, only: [:show]
  #get '/market', to: 'pages#market', as: 'market'
  #get '/hotel/busca', to: 'locations#index'
  #get '/user/sign_up', to: 'devices#registration'
  #get '/user/sign_in', to 'devices#registration'
  #get '/pets/new', to 'pets#new'
  #post '/pets', to 'pets#create'
  #get '/reservations/new', to 'reservations#reservations#new'
  #get '/guests', to 'reservations#guests'
  #patch '/updatereservation', to 'reservations#updatereservations'
  #delete 'reservations/:id', to 'reservations#destroy'
  #get '/hosts/sign_up', to 'hosts#hosts#new'
  #get 'reservation/:id', to 'reservations#reservations#show'
  #get '/reservation/new', to 'reservations#reservations#new'
  #get '/reservations/:id/edit', to 'reservations#reservations#edit'
  #patch '/reservations/:id', to 'reservations#reservations#update'
  #get '/location/:id/edit', to 'locations#locations#edit'
  #patch '/location/:id', to 'locations#locations#update'
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  SIZE_KG = ["Mini: 0-5kg", "Pequeno: 5-10kg", "Médio: 10-20kg", "Grande: 20-40kg", "Gigante: +40kg"]
  BREED = ["Akita",
  "Basset hound",
  "Beagle",
  "Bichon frisé",
  "Boiadeiro australiano",
  "Border collie",
  "Boston terrier",
  "Boxer",
  "Buldogue francês",
  "Buldogue inglês",
  "Bull terrier",
  "Cane corso",
  "Cavalier king charles spaniel",
  "Chihuahua",
  "Chow chow",
  "Cocker spaniel inglês",
  "Dachshund",
  "Dálmata",
  "Doberman",
  "Dogo argentino",
  "Dogue alemão",
  "Fila brasileiro",
  "Golden retriever",
  "Husky siberiano",
  "Jack russell terrier",
  "Labrador retriever",
  "Lhasa apso",
  "Lulu da pomerânia",
  "Maltês",
  "Mastiff inglês",
  "Mastim tibetano",
  "Pastor alemão",
  "Pastor australiano",
  "Pastor de Shetland",
  "Pequinês",
  "Pinscher",
  "Pit bull",
  "Poodle",
  "Pug",
  "Rottweiler",
  "Schnauzer",
  "Shar-pei",
  "Shiba",
  "Shih tzu",
  "Staffordshire bull terrier",
  "Weimaraner",
  "Yorkshire",
  "SRD",
  "Outra"]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to profile_show_path(current_user)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to user_path(current_user)
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :size_kg, :breed, :weight, :photo)
  end

end

app/views/pets/edit.html.erb
<div class= "container">
<h1>Edite seu pet</h1>

<%= simple_form_for @pet, as: :pet, url: pet_path(@pet), method: :patch do |f| %>
<%= f.input :name %>
<%= f.input  :size_kg, collection: Pet::SIZE_KG.map { |e| e.capitalize}, include_blank: false %>
<%= f.input  :breed, collection: Pet::BREED.map { |e| e.capitalize}, include_blank: false  %>
<%= f.submit "Editar Bicho", class:"btn btn-primary"%>
<% end %>
</div>

app/views/pets/new.html.erb
<div class= "container">
<h1>Adicione seu pet</h1>

<%= simple_form_for @pet, as: :pet, url: pets_path(@pet), method: :post do |f| %>
<%= f.input :name %>
<%= f.input  :size_kg, collection: Pet::SIZE_KG.map { |e| e.capitalize}, include_blank: false %>
<%= f.input  :breed, collection: Pet::BREED.map { |e| e.capitalize}, include_blank: false  %>
<%= f.input :photo, as: :file %>
<%= f.submit "Adicionar Bicho", class:"btn btn-primary"%>
<% end %>
</div>