config/routes.rb
Rails.application.routes.draw do

  root to: "pages#market"
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :locations do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :index, :destroy]

  # resources :devices, only: [:new, :create]

  resources :pets, only: [:new, :create, :edit, :update, :destroy]
  # resources :users, only: [:show, :edit, :update]

  resources :location, only: [:show]


  get '/profile', to: 'pages#profile', as: 'profile'
  get '/profile/:id', to: 'pages#profile', as: 'profile_show'


  # resources :users, only: [:show]
  #get '/market', to: 'pages#market', as: 'market'
  #get '/hotel/busca', to: 'locations#index'
  #get '/user/sign_up', to: 'devices#registration'
  #get '/user/sign_in', to 'devices#registration'
  #get '/pets/new', to 'pets#new'
  #post '/pets', to 'pets#create'
  #get '/reservations/new', to 'reservations#reservations#new'
  #get '/guests', to 'reservations#guests'
  #patch '/updatereservation', to 'reservations#updatereservations'
  #delete 'reservations/:id', to 'reservations#destroy'
  #get '/hosts/sign_up', to 'hosts#hosts#new'
  #get 'reservation/:id', to 'reservations#reservations#show'
  #get '/reservation/new', to 'reservations#reservations#new'
  #get '/reservations/:id/edit', to 'reservations#reservations#edit'
  #patch '/reservations/:id', to 'reservations#reservations#update'
  #get '/location/:id/edit', to 'locations#locations#edit'
  #patch '/location/:id', to 'locations#locations#update'
end

app/views/shared/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->


  <footer class="bg-light text-center text-lg-start text-dark">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row my-4">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">

          <div class="rounded-circle bg-white shadow-1-strong d-flex align-items-center justify-content-center mb-4 mx-auto" style="width: 150px; height: 150px;">
            <img src="https://mdbootstrap.com/img/Photos/new-templates/animal-shelter/logo.png" height="70" alt=""
                 loading="lazy" />
          </div>

          <p class="text-center">Encontre os melhores tios de pet!</p>

          <ul class="list-unstyled d-flex flex-row justify-content-center">
            <li>
              <a class="text-dark px-2" href="#!">
                <i class="fab fa-facebook-square"></i>
              </a>
            </li>
            <li>
              <a class="text-dark px-2" href="#!">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            <li>
              <a class="text-dark ps-2" href="#!">
                <i class="fab fa-youtube"></i>
              </a>
            </li>
          </ul>

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-4">Sobre nós</h5>

          <ul class="list-unstyled">
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Log In</a>
            </li>
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Hospedagens</a>
            </li>
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Seja um tio de pet</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-4">Saiba mais</h5>

          <ul class="list-unstyled">
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Política de privacidade</a>
            </li>
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Termos de uso</a>
            </li>
            <li class="mb-2">
              <a href="#!" class="text-dark"><i class="fas fa-paw pe-3"></i>Ajuda</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-4">Fale conosco</h5>

          <ul class="list-unstyled">
            <li>
              <p><i class="fas fa-map-marker-alt pe-2"></i>Wall Street Court - Nova York, US</p>
            </li>
            <li>
              <p><i class="fas fa-phone pe-2"></i>+ 01 234 567 89</p>
            </li>
            <li>
              <p><i class="fas fa-envelope pe-2 mb-0"></i>contact@lovemypet.com</p>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2022 Copyright:
      <a class="text-dark" href="https://lovemypet.com">lovemypet.com</a>
    </div>
    <!-- Copyright -->
  </footer>


<!-- End of .container -->

app/views/shared/_navbar.html.erb
<div class="bg-light navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "pet_love.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <!--li class="nav-item active"-->
            <%#= link_to "Home", "/", class: "nav-link" %>
          <!--/li-->
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline-secondary ml-4" %>
          <!--/li-->
          <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, width: 40, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Meu Perfil", profile_path, class: "dropdown-item" %>
              <%#= link_to "Meu Perfil", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Minhas Reservas", reservations_path, class: "dropdown-item" %>
              <%= link_to "Cadastrar Pet", new_pet_path, class: "dropdown-item" %>
              <%= link_to "Cadastrar Hospedagem", new_location_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline-secondary ml-4" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>