config/routes.rb
Rails.application.routes.draw do

  root to: "pages#market"
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :locations do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :index, :destroy]

  # resources :devices, only: [:new, :create]

  resources :pets, only: [:new, :create, :edit, :update, :destroy]
  # resources :users, only: [:show, :edit, :update]

  resources :location, only: [:show]


  get '/profile', to: 'pages#profile', as: 'profile'
  get '/profile/:id', to: 'pages#profile', as: 'profile_show'


  # resources :users, only: [:show]
  #get '/market', to: 'pages#market', as: 'market'
  #get '/hotel/busca', to: 'locations#index'
  #get '/user/sign_up', to: 'devices#registration'
  #get '/user/sign_in', to 'devices#registration'
  #get '/pets/new', to 'pets#new'
  #post '/pets', to 'pets#create'
  #get '/reservations/new', to 'reservations#reservations#new'
  #get '/guests', to 'reservations#guests'
  #patch '/updatereservation', to 'reservations#updatereservations'
  #delete 'reservations/:id', to 'reservations#destroy'
  #get '/hosts/sign_up', to 'hosts#hosts#new'
  #get 'reservation/:id', to 'reservations#reservations#show'
  #get '/reservation/new', to 'reservations#reservations#new'
  #get '/reservations/:id/edit', to 'reservations#reservations#edit'
  #patch '/reservations/:id', to 'reservations#reservations#update'
  #get '/location/:id/edit', to 'locations#locations#edit'
  #patch '/location/:id', to 'locations#locations#update'
end

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/market.html.erb
<main>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path "pets_banner.jpg"%>); background-size: cover;">
    <div class="container py-4 ">
      <div class="p-5 mb-4 bg-gradient-light rounded-3 text-white">
        <div class="container-fluid py-5 ">
          <h1 class="display-5 fw-bold ">Love My Pet</h1>
          <p class="col-md-8 fs-4">A maior pagina de hospedagem do seu bicho</p>
          <p>Encontre o melhor local para hospedar o seu amigo com total conforto e segurança</p>
          <%= link_to "Hospedagens", locations_path, class: "btn btn-primary btn-lg"%>
        </div>
      </div>
      <div class="row align-items-md-stretch">
        <%# <div class="col-md-6"> %>
          <%# <div class="h-100 p-5 text-white bg-dark rounded-3 opacity-75">
            <h2>Change the background</h2>
            <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
            <button class="btn btn-outline-light" type="button">Example button</button>
          </div> %>
        <%# </div> %>
        <div class="col-md-6">
          <div class="h-100 p-5 bg-light border rounded-3 opacity-75">
            <h2>Seja um tio de bicho</h2>
            <p>Vem ver como a gente conecta quem tem bicho a tios que cuidam deles no dia e na hora que você precisar!</p>
            <%= link_to "Adicionar Hospedagem", new_location_path, class: "btn btn-outline-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/pages/profile.html.erb
<div class="container shadow-sm p-3 mb-5 bg-white rounded mt-4" >
    <div class="cover mb-4 d-flex align-items-center justify-content-center">
      <div class="text-center">
        <h1>Meu perfil</h1>
        <div>
        <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, width: 150, class: "avatar dropdown-toggle", style:"margin-left: auto; margin-right: auto;"%>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", style:"width: 150px; margin-left: auto; margin-right: auto;"%>
          <% end %>
        </div>
        <h3 class="typed-js" data-controller="typed-js"></h3>
      </div>
    </div>

    <%# PERFIL USUÁRIO %>
    <form class="row">
      <%if @user.name?  %>
        <div class="col-md-6">
          <label class="form-label">Nome</label>
          <input type="text" class="form-control" value="<%=@user.name%>">
        </div>
      <%else  %>
        <div class="col-md-6">
          <label class="form-label">Nome</label>
          <input type="text" class="form-control" placeholder="Nome">
        </div>
      <%end %>
      <div class="col-md-6">
        <label class="form-label">Email</label>
        <input type="text" class="form-control" value="<%=@user.email%>">
      </div>
      <div class="col-md-12">
        <label class="form-label">Endereço</label>
         <input type="text" class="form-control" value="<%=@user.address%>">
      </div>
       <div class="mt-2">
          <%= link_to "Editar perfil", edit_user_registration_path, class: "btn btn-outline-warning ml-4", data: {turbo: false} %>
       </div>
    </form>
</div>
    <%# ADICIONAR BICHO  %>

<div class="container shadow-sm p-3 mb-5 bg-white rounded">
  <div class="cover mb-4 d-flex align-items-center justify-content-center">
    <div class="text-center">
      <h1>Meus bichos</h1>
      <h3 class="typed-js" data-controller="typed-js"></h3>
    </div>
  </div>
  <div class="row justify-content-around">
    <%@pets.each do |pet|%>
      <div class="card ml-3 mt-2" style="width: 18rem;">
        <% if pet.photo.attached?%>
        <%= cl_image_tag pet.photo.key, width: 925, class: "pet-img"%>
        <% else %>
        <img src="https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&w=600" style="border-radius: 5%; margin-top: 1rem;" class="card-img-top" alt="...">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= pet.name %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><i class="fa-solid fa-paw"></i> Raça: <%= pet.breed %></li>
          <li class="list-group-item"><i class="fa-solid fa-weight-scale"></i> Peso: <%= pet.size_kg %> kg</li>

        </ul>
        <div class="card-body">
          <a href="<%= edit_pet_path(pet) %>" class="btn btn-outline-secondary">Editar</a>
         <%= link_to "Deletar Pet", pet_path(pet), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Você tem certeza?"} %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
    <%= link_to "Adicionar bicho", new_pet_path, class: "btn btn-outline-warning ml-4 mt-4" %>
  </div>
</div>
      <%# ADICIONAR LOCAIS %>
<div class="container shadow-sm p-3 mb-5 bg-white rounded">
  <div class="cover mb-4 d-flex align-items-center justify-content-center">
    <div class="text-center">
      <h1>Meus Locais</h1>
      <h3 class="typed-js" data-controller="typed-js"></h3>
    </div>
  </div>
  <div class="row justify-content-around">
    <% if @locations.nil? %>
      <h3>Nenhum local cadastrado</h3>
    <% else %>
      <%@locations.each do |location|%>
        <div class="card ml-3 mt-2" style="width: 18rem;">
        <% if location.photo.attached?%>
        <%= cl_image_tag location.photo.key, width: 373, class: "location-img"%>
        <% else %>
          <img src="https://burst.shopifycdn.com/photos/brick-country-house.jpg?width=373&format=pjpg&exif=1&iptc=1" style="border-radius: 5%; margin-top: 1rem;" class="card-img-top" alt="...">
        <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= location.address %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><i class="fas fa-home"></i> Moradia: <%= location.home_type %></li>
            <li class="list-group-item"><i class="fa-solid fa-warehouse"></i> Capacidade: <%= location.total_occupancy %></li>
            <li class="list-group-item"><i class="fa fa-list-alt" aria-hidden="true"></i> Resumo: <%= location.summary %></li>
          </ul>
          <div class="card-body">
            <a href="<%= edit_location_path(location) %>" class="btn btn-outline-secondary">Editar</a>
          <%= link_to "Deletar location", location_path(location), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Você tem certeza?"} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div>
    <%= link_to "Adicionar hospedagem", new_location_path, class: "btn btn-outline-warning ml-4 mb-3 mt-5" %>
  </div>
</div>

<%#@pets.each do |pet|%>
<%#= pet.name %>
<%#= pet.breed %>
<%# end %>
<%#= link_to "Cadastrar Pet" new_pet_path, class: "newpet-link btn btn-outline-secondary ml-4"%>