config/routes.rb
Rails.application.routes.draw do

  root to: "pages#market"
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :locations do
    resources :reservations, only: [:new, :create]
  end
  resources :reservations, only: [:show, :edit, :update, :index, :destroy]

  # resources :devices, only: [:new, :create]

  resources :pets, only: [:new, :create, :edit, :update, :destroy]
  # resources :users, only: [:show, :edit, :update]

  resources :location, only: [:show]


  get '/profile', to: 'pages#profile', as: 'profile'
  get '/profile/:id', to: 'pages#profile', as: 'profile_show'


  # resources :users, only: [:show]
  #get '/market', to: 'pages#market', as: 'market'
  #get '/hotel/busca', to: 'locations#index'
  #get '/user/sign_up', to: 'devices#registration'
  #get '/user/sign_in', to 'devices#registration'
  #get '/pets/new', to 'pets#new'
  #post '/pets', to 'pets#create'
  #get '/reservations/new', to 'reservations#reservations#new'
  #get '/guests', to 'reservations#guests'
  #patch '/updatereservation', to 'reservations#updatereservations'
  #delete 'reservations/:id', to 'reservations#destroy'
  #get '/hosts/sign_up', to 'hosts#hosts#new'
  #get 'reservation/:id', to 'reservations#reservations#show'
  #get '/reservation/new', to 'reservations#reservations#new'
  #get '/reservations/:id/edit', to 'reservations#reservations#edit'
  #patch '/reservations/:id', to 'reservations#reservations#update'
  #get '/location/:id/edit', to 'locations#locations#edit'
  #patch '/location/:id', to 'locations#locations#update'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  
  HOME_TYPE = ["casa", "canil", "apartamento", "chácara / Fazenda"]
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    if @location.save
      redirect_to profile_show_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.update(location_params)
    redirect_to profile_show_path(current_user)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to profile_show_path(current_user)
  end


  private

  def location_params
    params.require(:location).permit(:address, :home_type, :total_occupancy, :summary, :price, :photo)
  end
end

app/views/locations/edit.html.erb
<div class= "container">
  <h1>Editar uma hospedagem</h1>

  <%= simple_form_for @location, as: :location, url: location_path(@location), method: :patch do |f| %>
    <%= f.input :address %>
    <%= f.input  :home_type, collection: Location::HOME_TYPE.map { |e| e.capitalize}, include_blank: false %>
    <%= f.input  :total_occupancy %>
    <%= f.label "Preço por Dia"%>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">R$</span>
    </div>
    <%= f.input :price, class:"form-control", label:false, input_html:{type:"number",min:0} %>
    <div class="input-group-append">
      <span class="input-group-text">.00</span>
    </div>
  </div>

  <%= f.label :summary %>
    <%= f.text_area  :summary, class: "mx-auto w-100" %>
    <%= f.submit "Editar hospedagem", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/locations/index.html.erb
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.tegraincorporadora.com.br/CMS/posts/315/cachorro-cobertor.jpg)">
    Escolha o lar ideal para o seu Pet 🐾
</div>

  <div class="py-4 mt-2 mb-2 w-100 d-flex align-items-center justify-content-center">
  <form class="row">
    <label for="date" class="col-2 col-form-label">Check-In</label>
    <div class="col-4">
      <div class="input-group date" id="datepicker">
        <input type="text" class="form-control bg-white" id="date"/>
        <span class="input-group-append">
          <span class="input-group-text bg-light d-block">
            <i class="fa fa-calendar"></i>
          </span>
        </span>
      </div>
    </div>
   <label for="date" class="col-2 col-form-label">Check-Out</label>
    <div class="col-4">
      <div class="input-group date" id="datepicker">
        <input type="text" class="form-control bg-white" id="date"/>
        <span class="input-group-append">
          <span class="input-group-text bg-light d-block">
            <i class="fa fa-calendar"></i>
          </span>
        </span>
      </div>
    </div>
  </form>
    </div>
<div class="container mb-5">
  <div class="cards">

    <% @locations.each do |location| %>
      <div class="card-product">
        <% if location.photo.attached?%>
          <%= cl_image_tag location.photo.key, width: 620%>
        <% else %>
          <img src="https://s2.glbimg.com/zNn8NIWzdwXHz2pEoSlz76DaG30=/620x550/e.glbimg.com/og/ed/f/original/2018/03/13/caes-branco-jardim-vasos-pedras-madeira-flores.jpg" />
        <% end %>
          <div class="card-product-infos">
            <h2><%= location.user.name %></h2>
            <p><strong>R$<%= location.price %>,00 p/ dia</strong></p>
            <p><%= location.address %></p>
            <%= link_to "Reservar esse espaço!",  new_location_reservation_path(location)%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/locations/new.html.erb
<div class= "container">
  <h1>Adicione uma hospedagem</h1>

  <%= simple_form_for @location, as: :location, url: locations_path(@location), method: :post do |f| %>
    <%= f.input :address %>
    <%= f.input  :home_type, collection: Location::HOME_TYPE.map { |e| e.capitalize}, include_blank: false %>
    <%= f.input  :total_occupancy %>
    <%= f.label "Preço por Dia"%>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">R$</span>
    </div>
    <%= f.input :price, class:"form-control", label:false, input_html:{type:"number",min:0} %>
    <div class="input-group-append">
      <span class="input-group-text">.00</span>
    </div>
  </div>

  <%= f.label :summary %>
    <%= f.text_area  :summary, class: "mx-auto w-100" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Cadastrar hospedagem", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/locations/show.html.erb
<h1>Locations Show</h1>

<!--Nesta pagina abrir o local e os pets que estão vinculados a este local-->
<!--rota: location GET  /locations/:id(.:format)  locations#show-->

<div class="container shadow-sm p-3 mb-5 bg-white rounded">
  <div class="cover mb-4 d-flex align-items-center justify-content-center">
    <div class="text-center">
      <h1>Reservas</h1>
      <h3 class="typed-js" data-controller="typed-js"></h3>
    </div>
  </div>
  <div class="row justify-content-around">
    <% if @locations.nil? %> <!-- ou reservations? -->
      <h3>Nenhuma Reserva</h3>
    <% else %>
      <%@locations.each do |location|%>
        <div class="card ml-3 mt-2" style="width: 18rem;">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" style="border-radius: 5%; margin-top: 1rem;" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= location.address %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><i class="fas fa-home"></i> Moradia: <%= location.home_type %></li>
            <li class="list-group-item"><i class="fa-solid fa-warehouse"></i> Capacidade: <%= location.total_occupancy %></li>
            <li class="list-group-item"><i class="fa fa-list-alt" aria-hidden="true"></i> Resumo: <%= location.summary %></li>
          </ul>
          <div class="card-body">
            <a href="<%= edit_location_path(location) %>" class="btn btn-outline-secondary">Editar</a>
          <%= link_to "Deletar location", location_path(location), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Você tem certeza?"} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div>
    <%= link_to "Adicionar hospedagem", new_location_path, class: "btn btn-outline-warning ml-4 mb-3 mt-5" %>
  </div>
</div>